# 02_recoleccion_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.

In [ ]:
# Inicio del análisis


# 2. Recolección e integración de datos
     - Contar la historia con los datos. 

1. Decribir el origen de los datos:
   * meteorológicos
   * epidemiológicos. 
2. Describir las variables y fundamentar su elección. 
   * meteorológicos
   * epidemiológicos.

## 2.1 Datos epidemiológicos

* Casos por fecha
* Municipio
* Semana epidemiológica


# Fuentes posibles:

* Secretaria de salud 


Variables típicas:

* Procedencia

# Obtención de los datos epidemiológicos estructurados por Janis e Idalina

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Importar datos
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Secretaria de salud\BD_DENGUE_2021-2025_PROCE_CAUCASIA.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\6_datos_arima\datos_epidemiologicos_2021-2024.xlsx"
df_epi=pd.read_excel(ubicacion_janis)
df_epi.head(2)

,fec_not,semana,año,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,ndep_proce,nmun_proce,nmun_resi
0,2021-02-16,3,2021,2,NaN,CAUCASIA,NaN,CAUCASIA,CR 39 E 48 C SUR 36,ANTIOQUIA,CAUCASIA,ENVIGADO
1,2021-02-19,6,2021,2,NaN,CAUCASIA,NaN,CAUCASIA,CL 29 A 42-99,ANTIOQUIA,CAUCASIA,BOGOTA

# Selección de los atributos epidemológicos que se considerarán en la investigación

1. Fecha de notificación (fec_not)
2. Año (año)
3. Barrios (bar_ver)
4. Municipio de procedencia (nmun_proce) para este análisis es Caucasia


## 2.2 Datos meteorológicos

Fuentes posibles:

* NASA POWER

# Obtención de los datos meteorológicos o variables exógenas.

In [6]:
# Importar datos
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos meteorológicos\Datos_NS_2021-2025.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\6_datos_arima\datos_meteorologicos_2021-2024.csv"
df_meteo=pd.read_excel(ubicacion_janis)
df_meteo.head(2)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,QV2M,RH2M,PRECTOTCORR,WS2M,WS2M_MAX,WS2M_MIN,UV
0,2021,1,28.38,34.96,23.58,16.62,71.66,3.59,0.14,0.24,0.02,2.48
1,2021,2,27.44,33.39,23.64,17.98,80.54,12.12,0.10,0.23,0.04,2.18

# Selección de los atributos

Variables típicas:

* Temperatura
* Precipitación
* Humedad relativa
* Humedad específica 
* UV
* Velocidad del viento