# 02_recoleccion_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.

In [ ]:
# Inicio del análisis


# 2. Recolección e integración de datos
     - Contar la historia con los datos.

## 2.1 Datos epidemiológicos

* Casos por fecha
* Municipio
* Semana epidemiológica


# Fuentes posibles:

* Secretaria de salud 


Variables típicas:

* Procedencia

# Obtención de los datos epidemiológicos estructurados por Janis e Idalina

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
# Importar datos
ubicacion_janis = r""
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\6_datos_arima\datos_epidemiologicos_2021-2024.xlsx"
df_epi=pd.read_excel(ubicacion_marco)
df_epi.head(2)

,cod_eve,fec_not,semana,año,cod_pre,cod_sub,edad_,uni_med_,nacionali_,nombre_nacionalidad,...,nom_upgd,npais_proce,ndep_proce,nmun_proce,npais_resi,ndep_resi,nmun_resi,ndep_notif,nmun_notif,nreg
0,210,2021-01-11,1,2021,515402201,1,40,1,170,COLOMBIA,...,ESE HOSPITAL CESAR URIBE PIEDRAHITA,COLOMBIA,ANTIOQUIA,EL BAGRE,COLOMBIA,ANTIOQUIA,EL BAGRE,ANTIOQUIA,CAUCASIA,1800
1,210,2021-02-06,5,2021,515402201,1,12,1,170,COLOMBIA,...,ESE HOSPITAL CESAR URIBE PIEDRAHITA,COLOMBIA,ANTIOQUIA,ZARAGOZA,COLOMBIA,ANTIOQUIA,ZARAGOZA,ANTIOQUIA,CAUCASIA,1791


## 2.2 Datos meteorológicos

Fuentes posibles:

* NASA POWER
* IDEAM
* Antioquia Mira su Cielo
* Fedearroz

Variables típicas:

* temperatura
* precipitación
* humedad
* radiación
* velocidad del viento

# Obtención de los datos meteorológicos o variables exógenas.

In [8]:
# Importar datos
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos meteorológicos\NASA POWER\Datos_NS_2021-2024.csv"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\6_datos_arima\datos_meteorologicos_2021-2024.csv"
df_meteo=pd.read_csv(ubicacion_marco, sep = ';')
df_meteo.head(2)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,QV2M,RH2M,PRECTOTCORR,WS2M,WS2M_MAX,WS2M_MIN,UV
0,2021,1,28.38,34.96,23.58,16.62,71.66,3.59,0.14,0.24,0.02,2.48
1,2021,2,27.44,33.39,23.64,17.98,80.54,12.12,0.10,0.23,0.04,2.18