# 02_recoleccion_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.

In [ ]:
# Inicio del análisis


# 2. Recolección e integración de datos
     - Contar la historia con los datos. 

1. Decribir el origen de los datos:
   * meteorológicos
   * epidemiológicos. 
2. Describir las variables y fundamentar su elección. 
   * meteorológicos
   * epidemiológicos.

## 2.1 Datos epidemiológicos

* Casos por fecha
* Municipio
* Semana epidemiológica


# Fuentes posibles:

* Secretaria de salud 


Variables típicas:

* Procedencia

# Obtención de los datos epidemiológicos estructurados por Janis e Idalina

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# Importar datos epidemiológicos 
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Secretaria de salud\BD_DENGUE_2021-2025_PROCE_CAUCASIA.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\arima\6_datos_arima\datos_version_marzo_16_2026\datos_epidemiologicos_2021-2025.xlsx"
df_epi=pd.read_excel(ubicacion_marco)
df_epi.head(2)

,ini_sin_,semana,año,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,nmun_proce,nmun_resi
0,2021-01-21,3,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CR 39 E 48 C SUR 36,CAUCASIA,ENVIGADO
1,2021-02-08,6,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CL 29 A 42-99,CAUCASIA,BOGOTA

# Selección de los atributos epidemológicos que se considerarán en la investigación

1. Fecha  en que se iniciaron los síntomas de dengue (fec_not)
2. Año (año)
3. Barrios (bar_ver)
4. Municipio de procedencia (nmun_proce) para este análisis es Caucasia


## 2.2 Datos meteorológicos

Fuentes posibles:

* NASA POWER

# Obtención de los datos meteorológicos o variables exógenas.

In [5]:
# Importar datos meteorológicos 
ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos meteorológicos\Datos_NS_2021-2025.xlsx"
ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\arima\6_datos_arima\datos_version_marzo_16_2026\datos_meteorologicos_2021-2025.xlsx"
df_meteo=pd.read_excel(ubicacion_marco)
df_meteo.head(2)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,QV2M,RH2M,PRECTOTCORR,WS2M,WS2M_MAX,WS2M_MIN,ALLSKY_SFC_UV_INDEX
0,2021,3,28.64,35.09,23.84,17.89,75.41,4.03,0.14,0.32,0.07,2.48
1,2021,4,28.48,35.05,23.69,15.91,68.69,0.70,0.14,0.25,0.07,2.47

# Selección de los atributos

Variables típicas:

* Temperatura
* Precipitación
* Humedad relativa
* Humedad específica 
* UV
* Velocidad del viento