# 03_limpieza_datos

Proyecto ARIMA / ARIMAX
Modelación epidemiológica con variables meteorológicas.

# Obtención de los datos epidemiológicos

In [2]:
# Inicio del análisis
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
# Importar datos epidemiológicos 
ubicacion_epi_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Secretaria de salud\BD_DENGUE_2021-2025_CAUCASIA.xlsx"
ubicacion_epi_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\3_datos_version_6_abril_2026\epidemiologicos.xlsx"
df_epi_caucasia=pd.read_excel(ubicacion_epi_janis)

# Importar datos meteorológicos 
ubicacion_meteo_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos meteorológicos\Datos_NS_2021-2025_SOI-SST.xlsx"
ubicacion_meteo_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\3_datos_version_6_abril_2026\meteorologicos.xlsx"
df_meteo_caucasia=pd.read_excel(ubicacion_meteo_janis)

In [5]:
df_epi_caucasia.head(2)

,ini_sin_,semana,año,area_,localidad_,cen_pobla_,vereda_,bar_ver_,dir_res_,nmun_proce,nmun_resi
0,2021-01-21,3,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CR 39 E 48 C SUR 36,CAUCASIA,ENVIGADO
1,2021-02-08,6,2021,2,NO APLICA,CAUCASIA,NO APLICA,CAUCASIA,CL 29 A 42-99,CAUCASIA,BOGOTA

In [6]:
df_meteo_caucasia.head(2)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,QV2M,RH2M,PRECTOTCORR,WS2M,WS2M_MAX,WS2M_MIN,ALLSKY_SFC_UV_INDEX,SOI,SST_ANOMALY
0,2021,3,28.33,35.09,23.84,18.15,78.13,5.83,0.13,0.32,0.07,2.48,23.42,-1.038442
1,2021,4,28.71,35.05,23.69,16.29,69.26,0.77,0.14,0.30,0.07,2.47,25.40,-1.071886

In [7]:
df_meteo_caucasia.columns

Index(['YEAR', 'DOY', 'T2M', 'T2M_MAX', 'T2M_MIN', 'QV2M', 'RH2M',
       'PRECTOTCORR', 'WS2M', 'WS2M_MAX', 'WS2M_MIN', 'ALLSKY_SFC_UV_INDEX',
       'SOI', 'SST_ANOMALY'],
      dtype='object')

In [8]:
df_epi_caucasia.columns

Index(['ini_sin_', 'semana', 'año', 'area_', 'localidad_', 'cen_pobla_',
       'vereda_', 'bar_ver_', 'dir_res_', 'nmun_proce', 'nmun_resi'],
      dtype='object')

# Remuestreo de los datos Epidemiológicos a frecuencia semanal

In [9]:
# remuestreo epidemiológico 2024 y 2025. 2021 al 2024 con 52 semanas, 2025 con 53 semanas
# ---------------------------
# 1. AGRUPAR CASOS POR SEMANA REAL
# ---------------------------
df_epi = df_epi_caucasia.copy()

df_semanal = df_epi.groupby(['año', 'semana']).size().reset_index(name='num_casos')


# ---------------------------
# 2. ESTRUCTURA 2021–2024 (52 semanas)
# ---------------------------
estructura_1 = pd.MultiIndex.from_product(
    [range(2021, 2025), range(1, 53)],
    names=['año', 'semana']
).to_frame(index=False)

df_1_epi = pd.merge(estructura_1, df_semanal, on=['año', 'semana'], how='left')
df_1_epi['num_casos'] = df_1_epi['num_casos'].fillna(0).astype(int)


# ---------------------------
# 3. ESTRUCTURA 2025 (53 semanas)
# ---------------------------
estructura_2 = pd.DataFrame({
    'año': [2025]*53,
    'semana': range(1, 54)
})

df_2_epi = pd.merge(estructura_2, df_semanal, on=['año', 'semana'], how='left')
df_2_epi['num_casos'] = df_2_epi['num_casos'].fillna(0).astype(int)


# ---------------------------
# 4. FECHAS CORRECTAS (CLAVE)
# ---------------------------
inicios = {
    2021: '2021-01-03',
    2022: '2022-01-02',
    2023: '2023-01-01',
    2024: '2023-12-31',  # ← corrige el error de 25 vs 22 dic
    2025: '2024-12-29'
}

def asignar_fecha(row):
    inicio = pd.Timestamp(inicios[row['año']])
    return inicio + pd.to_timedelta((row['semana'] - 1) * 7, unit='D')


# Aplicar
df_1_epi['fecha'] = df_1_epi.apply(asignar_fecha, axis=1)
df_2_epi['fecha'] = df_2_epi.apply(asignar_fecha, axis=1)


# ---------------------------
# 5. UNIR TODO
# ---------------------------
df_final_epi = pd.concat([df_1_epi, df_2_epi])

df_final_epi = df_final_epi.sort_values('fecha').set_index('fecha')
df_final_epi = df_final_epi.rename(columns={'semana': 'semana_epi'})

In [10]:
df_1_epi

      año  semana  num_casos      fecha
0    2021       1          0 2021-01-03
1    2021       2          0 2021-01-10
2    2021       3          1 2021-01-17
3    2021       4          0 2021-01-24
4    2021       5          0 2021-01-31
..    ...     ...        ...        ...
203  2024      48         68 2024-11-24
204  2024      49         92 2024-12-01
205  2024      50         85 2024-12-08
206  2024      51         74 2024-12-15
207  2024      52         66 2024-12-22

[208 rows x 4 columns]

In [11]:
df_2_epi

     año  semana  num_casos      fecha
0   2025       1         92 2024-12-29
1   2025       2         90 2025-01-05
2   2025       3         82 2025-01-12
3   2025       4         99 2025-01-19
4   2025       5        103 2025-01-26
5   2025       6        106 2025-02-02
6   2025       7         71 2025-02-09
7   2025       8         78 2025-02-16
8   2025       9         52 2025-02-23
9   2025      10         83 2025-03-02
10  2025      11         63 2025-03-09
11  2025      12         76 2025-03-16
12  2025      13         48 2025-03-23
13  2025      14         48 2025-03-30
14  2025      15         51 2025-04-06
15  2025      16         51 2025-04-13
16  2025      17         55 2025-04-20
17  2025      18         65 2025-04-27
18  2025      19         75 2025-05-04
19  2025      20         73 2025-05-11
20  2025      21         74 2025-05-18
21  2025      22         55 2025-05-25
22  2025      23         63 2025-06-01
23  2025      24         48 2025-06-08
24  2025      25         60 2025-06-15
25  2025      26         40 2025-06-22
26  2025      27         55 2025-06-29
27  2025      28         37 2025-07-06
28  2025      29         52 2025-07-13
29  2025      30         35 2025-07-20
30  2025      31         37 2025-07-27
31  2025      32         27 2025-08-03
32  2025      33         40 2025-08-10
33  2025      34         26 2025-08-17
34  2025      35         28 2025-08-24
35  2025      36         37 2025-08-31
36  2025      37         34 2025-09-07
37  2025      38         29 2025-09-14
38  2025      39         28 2025-09-21
39  2025      40         29 2025-09-28
40  2025      41         12 2025-10-05
41  2025      42         19 2025-10-12
42  2025      43         14 2025-10-19
43  2025      44         21 2025-10-26
44  2025      45         26 2025-11-02
45  2025      46         28 2025-11-09
46  2025      47         30 2025-11-16
47  2025      48         19 2025-11-23
48  2025      49          8 2025-11-30
49  2025      50          9 2025-12-07
50  2025      51          7 2025-12-14
51  2025      52          5 2025-12-21
52  2025      53          9 2025-12-28

### Meteorológicos

In [12]:
# Renombrar columnas del dataframe nasa
df_meteo_caucasia.rename(columns={
    'YEAR': 'año',
    'DOY': 'dia',
    'T2M': 'temp',
    'T2M_MAX': 'temp_max',
    'T2M_MIN': 'temp_min',
    'QV2M': 'hum_esp',
    'RH2M': 'hum_rel',
    'PRECTOTCORR': 'prec',
    'WS2M': 'vel_vi',
    'WS2M_MAX': 'vel_vi_max',
    'WS2M_MIN': 'vel_vi_min',
    'ALLSKY_SFC_UV_INDEX': 'uv',
    'SOI': 'soi',
    'SST_ANOMALY':'sst'
}, inplace=True)
df_meteo_caucasia.head(3)

,año,dia,temp,temp_max,temp_min,hum_esp,hum_rel,prec,vel_vi,vel_vi_max,vel_vi_min,uv,soi,sst
0,2021,3,28.33,35.09,23.84,18.15,78.13,5.83,0.13,0.32,0.07,2.48,23.42,-1.038442
1,2021,4,28.71,35.05,23.69,16.29,69.26,0.77,0.14,0.30,0.07,2.47,25.40,-1.071886
2,2021,5,27.85,34.96,22.71,15.36,69.34,0.80,0.16,0.34,0.03,2.30,20.07,-1.103086

In [13]:
df_meteo_caucasia.columns

Index(['año', 'dia', 'temp', 'temp_max', 'temp_min', 'hum_esp', 'hum_rel',
       'prec', 'vel_vi', 'vel_vi_max', 'vel_vi_min', 'uv', 'soi', 'sst'],
      dtype='object')

In [14]:
df_meteo = df_meteo_caucasia.copy()

# Crear fecha real
df_meteo['fecha'] = pd.to_datetime(df_meteo['año'].astype(str) + '-' + df_meteo['dia'].astype(str), format='%Y-%j')

In [15]:
df_meteo['dias_lluvia'] = (df_meteo['prec'] >= 1).astype(int)

In [16]:
inicios = {
    2021: pd.Timestamp('2021-01-03'),
    2022: pd.Timestamp('2022-01-02'),
    2023: pd.Timestamp('2023-01-01'),
    2024: pd.Timestamp('2023-12-31'),
    2025: pd.Timestamp('2024-12-29')
}

def asignar_semana(row):
    año = row['fecha'].year
    
    # Ajuste especial para fechas que pertenecen a semana epi del siguiente año
    if row['fecha'] >= inicios[2025]:
        año = 2025
    elif row['fecha'] >= inicios[2024]:
        año = 2024
    elif row['fecha'] >= inicios[2023]:
        año = 2023
    elif row['fecha'] >= inicios[2022]:
        año = 2022
    else:
        año = 2021

    semana = ((row['fecha'] - inicios[año]).days // 7) + 1
    return pd.Series([año, semana])

df_meteo[['año_epi', 'semana']] = df_meteo.apply(asignar_semana, axis=1)

In [17]:
df_semanal = df_meteo.groupby(['año_epi', 'semana']).agg({
    'temp': 'mean',
    'temp_max': 'mean',
    'temp_min': 'mean',
    'hum_esp': 'mean',
    'hum_rel': 'mean',
    'prec': 'mean',
    'dias_lluvia': 'sum',
    'vel_vi': 'mean',
    'vel_vi_max': 'mean',
    'vel_vi_min': 'mean',
    'uv': 'mean',
    'prec': 'sum',
    'soi': 'mean',
    'sst': 'mean'
}).reset_index()

df_semanal = df_semanal.rename(columns={'año_epi': 'año'})

In [18]:
estructura_1 = pd.MultiIndex.from_product(
    [range(2021, 2025), range(1, 53)],
    names=['año', 'semana']
).to_frame(index=False)

df_1_meteo = pd.merge(estructura_1, df_semanal, on=['año', 'semana'], how='left')

In [19]:
estructura_2 = pd.DataFrame({
    'año': [2025]*53,
    'semana': range(1, 54)
})

df_2_meteo = pd.merge(estructura_2, df_semanal, on=['año', 'semana'], how='left')

In [20]:
def asignar_fecha(row):
    inicio = inicios[row['año']]
    return inicio + pd.to_timedelta((row['semana'] - 1) * 7, unit='D')

df_1_meteo['fecha'] = df_1_meteo.apply(asignar_fecha, axis=1)
df_2_meteo['fecha'] = df_2_meteo.apply(asignar_fecha, axis=1)

In [21]:
df_final_meteo = pd.concat([df_1_meteo, df_2_meteo])
df_final_meteo = df_final_meteo.sort_values('fecha').set_index('fecha')

In [22]:
df_1_meteo

,año,semana,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,vel_vi,vel_vi_max,vel_vi_min,uv,soi,sst,fecha
0,2021,1,28.254286,34.200000,23.832857,16.367143,70.774286,7.73,1,0.124286,0.268571,0.047143,2.222857,20.067143,-1.060214,2021-01-03
1,2021,2,28.638571,34.910000,24.195714,17.318571,73.095714,19.18,5,0.111429,0.204286,0.038571,2.254286,18.207143,-1.058352,2021-01-10
2,2021,3,29.552857,36.372857,24.090000,16.122857,65.328571,0.80,0,0.122857,0.227143,0.045714,2.420000,10.847143,-0.931407,2021-01-17
3,2021,4,29.208571,35.978571,24.200000,16.564286,68.205714,12.81,5,0.122857,0.220000,0.035714,2.477143,15.430000,-0.837360,2021-01-24
4,2021,5,29.421429,35.882857,24.684286,17.311429,69.797143,18.06,3,0.117143,0.225714,0.030000,2.290000,9.348571,-0.897892,2021-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,2024,48,26.278571,29.455714,24.164286,19.707143,91.838571,43.67,7,0.157143,0.352857,0.040000,1.878571,16.867143,0.090169,2024-11-24
204,2024,49,26.570000,29.908571,24.212857,19.700000,90.314286,18.82,4,0.150000,0.322857,0.054286,1.762857,18.444286,-0.083963,2024-12-01
205,2024,50,26.778571,30.527143,23.577143,19.062857,86.507143,5.85,1,0.195714,0.518571,0.021429,1.921429,6.710000,-0.382062,2024-12-08
206,2024,51,26.618571,29.824286,24.062857,19.502857,89.172857,11.85,3,0.161429,0.472857,0.021429,1.652857,14.620000,-0.718384,2024-12-15
207,2024,52,26.024286,29.068571,23.940000,19.175714,90.857143,26.27,7,0.154286,0.418571,0.047143,1.724286,4.700000,-0.905041,2024-12-22

In [23]:
df_2_meteo

,año,semana,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,vel_vi,vel_vi_max,vel_vi_min,uv,soi,sst,fecha
0,2025,1,25.158571,28.048571,23.124286,18.602857,92.682857,73.12,7,0.158571,0.400000,0.030000,1.744286,-3.594286,-0.703858,2024-12-29
1,2025,2,26.551429,30.398571,23.624286,18.697143,86.357143,13.31,2,0.178571,0.421429,0.040000,1.871429,-4.187143,-0.750312,2025-01-05
2,2025,3,26.797143,31.061429,23.178571,18.377143,83.964286,0.80,0,0.180000,0.478571,0.032857,2.080000,-7.405714,-0.698161,2025-01-12
3,2025,4,26.945714,31.498571,23.451429,18.271429,82.832857,2.09,1,0.168571,0.460000,0.008571,1.988571,11.404286,-0.978982,2025-01-19
4,2025,5,27.128571,31.527143,24.010000,18.997143,84.857143,11.13,2,0.120000,0.272857,0.017143,1.947143,14.830000,-0.951556,2025-01-26
5,2025,6,27.062857,31.348571,23.768571,18.447143,82.987143,35.83,5,0.132857,0.320000,0.022857,1.775714,25.092857,-0.671806,2025-02-02
6,2025,7,26.912857,31.570000,23.697143,18.330000,83.498571,33.52,7,0.124286,0.240000,0.024286,1.754286,4.047143,-0.433545,2025-02-09
7,2025,8,27.505714,32.497143,24.010000,18.398571,81.260000,16.48,6,0.140000,0.290000,0.042857,1.890000,-7.480000,-0.278124,2025-02-16
8,2025,9,27.672857,32.394286,24.411429,18.815714,81.998571,25.08,5,0.134286,0.228571,0.060000,1.805714,4.460000,-0.186427,2025-02-23
9,2025,10,27.247143,32.092857,24.110000,18.282857,81.888571,23.79,6,0.137143,0.238571,0.060000,1.942857,4.984286,0.046518,2025-03-02
10,2025,11,28.310000,33.478571,24.430000,18.004286,76.250000,14.44,3,0.140000,0.265714,0.068571,1.938571,8.032857,0.286282,2025-03-09
11,2025,12,27.170000,31.085714,24.342857,19.054286,85.134286,69.05,6,0.132857,0.282857,0.060000,1.930000,9.332857,0.079298,2025-03-16
12,2025,13,27.852857,31.978571,24.962857,19.698571,84.498571,76.57,6,0.148571,0.318571,0.042857,2.071429,11.227143,0.246119,2025-03-23
13,2025,14,26.994286,30.720000,24.498571,19.191429,86.367143,40.39,6,0.132857,0.308571,0.045714,1.981429,13.048571,-0.052459,2025-03-30
14,2025,15,26.477143,28.944286,24.604286,19.758571,90.997143,50.35,6,0.150000,0.314286,0.057143,2.040000,9.938571,-0.047654,2025-04-06
15,2025,16,28.305714,32.841429,25.064286,19.792857,82.788571,17.54,5,0.125714,0.281429,0.014286,2.297143,-2.141429,-0.010803,2025-04-13
16,2025,17,26.685714,29.890000,24.270000,19.274286,87.914286,60.58,7,0.128571,0.287143,0.038571,2.271429,2.171429,0.092250,2025-04-20
17,2025,18,26.372857,29.260000,24.397143,19.650000,91.161429,66.80,7,0.147143,0.400000,0.032857,1.985714,-7.161429,0.138661,2025-04-27
18,2025,19,26.000000,28.920000,23.785714,19.272857,91.432857,79.98,7,0.138571,0.315714,0.024286,2.301429,-3.877143,0.231010,2025-05-04
19,2025,20,26.708571,29.487143,24.645714,20.201429,91.650000,39.09,7,0.137143,0.285714,0.038571,2.267143,1.037143,-0.000552,2025-05-11
20,2025,21,26.801429,29.858571,24.608571,20.154286,91.051429,26.24,7,0.130000,0.301429,0.025714,2.387143,2.195714,-0.017977,2025-05-18
21,2025,22,27.055714,30.155714,24.614286,20.331429,90.690000,22.40,6,0.124286,0.317143,0.010000,2.295714,17.408571,0.047865,2025-05-25
22,2025,23,26.442857,29.230000,24.432857,20.110000,92.797143,125.57,7,0.124286,0.271429,0.018571,2.090000,1.745714,0.141091,2025-06-01
23,2025,24,26.060000,28.372857,24.297143,19.850000,93.624286,57.32,7,0.135714,0.384286,0.018571,2.035714,-2.790000,0.174419,2025-06-08
24,2025,25,26.958571,29.994286,24.610000,20.431429,91.430000,112.81,7,0.140000,0.322857,0.024286,2.284286,-4.940000,0.233814,2025-06-15
25,2025,26,26.685714,29.725714,24.452857,20.154286,91.765714,56.37,7,0.138571,0.297143,0.024286,2.118571,8.222857,0.240936,2025-06-22
26,2025,27,26.887143,29.578571,24.678571,20.260000,90.977143,30.99,7,0.170000,0.424286,0.014286,2.280000,1.665714,0.294667,2025-06-29
27,2025,28,26.204286,29.070000,23.924286,19.548571,91.547143,32.00,5,0.170000,0.412857,0.018571,2.178571,2.418571,0.301245,2025-07-06
28,2025,29,27.181429,30.274286,24.428571,20.170000,89.021429,28.85,4,0.195714,0.458571,0.025714,2.484286,6.560000,0.070205,2025-07-13
29,2025,30,26.858571,29.497143,24.704286,20.317143,91.330000,29.74,6,0.160000,0.432857,0.014286,2.325714,9.550000,-0.114822,2025-07-20
30,2025,31,26.570000,29.447143,24.232857,19.975714,91.538571,32.64,4,0.150000,0.368571,0.017143,2.311429,7.115714,-0.177950,2025-07-27
31,2025,32,26.247143,29.065714,24.042857,19.515714,91.281429,37.28,7,0.171429,0.441429,0.022857,2.354286,-3.528571,-0.133827,2025-08-03
32,2025,33,25.965714,28.725714,23.808571,19.404286,92.200000,115.29,7,0.167143,0.402857,0.022857,2.134286,-3.555714,-0.192308,2025-08-10
33,2025,34,26.214286,29.491429,23.730000,19.480000,91.132857,63.38,6,0.168571,0.402857,0.022857,2.302857,-0.538571,-0.257709,2025-08-17
34,2025,35,27.020000,30.218571,24.592857,20.091429,89.810000,35.08,6,0.152857,0.398571,0.027143,2.464286,18.700000,-0.334617,2025-08-24
35,2025,36,26.410000,28.962857,24.484286,19.937143,92.147143,81.28,7,0.162857,0.362857,0.030000,2.282857,5.905714,-0.325527,2025-08-31
36,2025,37,26.294286,29.348571,24.122857,19.605714,91.395714,30.57,7,0.160000,0.354286,0.024286,2.447143,-4.208571,-0.353051,2025-09-07
37,2025,38,26.128571,28.951429,23.954286,19.411429,91.311429,71.24,6,0.158571,0.362857,0.027143,2.248571,-0.221429,-0.329364,2025-09-14
38,2025,39,26.394286,29.172857,24.344286,19.721429,91.332857,94.46,5,0.167143,0.378571,0.037143,2.422857,2.591429,-0.454914,2025-09-21
39,2025,40,25.597143,27.910000,23.795714,19.157143,92.925714,51.65,7,0.177143,0.375714,0.055714,2.175714,1.620000,-0.346037,2025-09-28
40,2025,41,25.688571,28.432857,23.674286,18.964286,91.567143,51.93,6,0.155714,0.357143,0.022857,2.060000,12.264286,-0.268223,2025-10-05
41,2025,42,25.507143,28.738571,23.202857,18.610000,90.937143,41.62,7,0.151429,0.345714,0.041429,2.102857,2.555714,-0.366160,2025-10-12
42,2025,43,26.087143,29.081429,23.865714,19.470000,91.762857,44.65,7,0.187143,0.437143,0.028571,2.127143,16.565714,-0.436933,2025-10-19
43,2025,44,26.130000,28.492857,24.451429,19.540000,91.732857,27.10,6,0.181429,0.397143,0.022857,2.327143,17.272857,-0.461052,2025-10-26
44,2025,45,26.055714,28.888571,23.968571,19.384286,91.568571,16.49,2,0.158571,0.344286,0.027143,2.138571,22.954286,-0.460149,2025-11-02
45,2025,46,25.944286,28.344286,24.287143,19.785714,93.798571,46.38,7,0.152857,0.332857,0.042857,2.005714,1.612857,-0.551520,2025-11-09
46,2025,47,25.598571,28.507143,23.415714,18.912857,91.805714,8.95,2,0.148571,0.322857,0.035714,2.042857,26.185714,-0.533567,2025-11-16
47,2025,48,25.954286,28.968571,23.862857,19.255714,91.417143,43.86,2,0.170000,0.377143,0.045714,1.904286,8.504286,-0.495016,2025-11-23
48,2025,49,25.527143,28.834286,23.218571,18.514286,90.482857,27.53,6,0.154286,0.375714,0.027143,2.065714,-22.127143,-0.355697,2025-11-30
49,2025,50,26.065714,29.091429,23.882857,19.224286,90.717143,21.56,4,0.170000,0.450000,0.034286,2.024286,3.128571,-0.552463,2025-12-07
50,2025,51,26.038571,29.442857,23.658571,18.982857,89.951429,30.71,6,0.160000,0.394286,0.034286,2.067143,1.335714,-0.602770,2025-12-14
51,2025,52,25.997143,30.090000,23.008571,17.992857,85.818571,2.49,1,0.185714,0.451429,0.018571,1.995714,7.732857,-0.644495,2025-12-21
52,2025,53,26.078571,29.490000,23.778571,19.051429,90.030000,14.34,3,0.135714,0.320000,0.025714,1.842500,6.411429,-0.618948,2025-12-28

# Unir las bases de datos epidemiológicas con la base de datos meteorológica de acuerdo al criterio año semana epidemiológica

In [25]:
# Unir datos
datos_semanal_meteo_epi = (
    pd.merge(
        df_final_epi.reset_index(),
        df_final_meteo.reset_index().drop(columns=['año', 'semana']),
        on='fecha',
        how='left'
    )
    .rename(columns={'num_casos': 'casos_dengue'})
)

# Quitar hora de la fecha
datos_semanal_meteo_epi['fecha'] = pd.to_datetime(datos_semanal_meteo_epi['fecha']).dt.date

# Reordenar columnas
columnas_orden = [
    'fecha',
    'año',
    'semana_epi',
    'temp', 'temp_max', 'temp_min',
    'hum_esp', 'hum_rel',
    'prec', 'dias_lluvia',
    'vel_vi', 'vel_vi_max', 'vel_vi_min',
    'uv', 'soi', 'sst', 'casos_dengue'
]

datos_semanal_meteo_epi = datos_semanal_meteo_epi[columnas_orden]

# Guardar
guardar_ubicacion_marco = r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\4_base_datos_consolidada\datos_semanal_meteo_epi.xlsx"
guardar_ubicacion_janis = r"C:\Users\usuario1\OneDrive - Universidad de Antioquia\UNIVERSIDAD DE ANTIOQUIA\Proyecto SAT Dengue\Bases de datos\Datos consolidados\datos_semanal_meteo_epi.xlsx"
datos_semanal_meteo_epi.to_excel(guardar_ubicacion_janis, index=False)

datos_semanal_meteo_epi.head()

,fecha,año,semana_epi,temp,temp_max,temp_min,hum_esp,hum_rel,prec,dias_lluvia,vel_vi,vel_vi_max,vel_vi_min,uv,soi,sst,casos_dengue
0,2021-01-03,2021,1,28.254286,34.200000,23.832857,16.367143,70.774286,7.73,1,0.124286,0.268571,0.047143,2.222857,20.067143,-1.060214,0
1,2021-01-10,2021,2,28.638571,34.910000,24.195714,17.318571,73.095714,19.18,5,0.111429,0.204286,0.038571,2.254286,18.207143,-1.058352,0
2,2021-01-17,2021,3,29.552857,36.372857,24.090000,16.122857,65.328571,0.80,0,0.122857,0.227143,0.045714,2.420000,10.847143,-0.931407,1
3,2021-01-24,2021,4,29.208571,35.978571,24.200000,16.564286,68.205714,12.81,5,0.122857,0.220000,0.035714,2.477143,15.430000,-0.837360,0
4,2021-01-31,2021,5,29.421429,35.882857,24.684286,17.311429,69.797143,18.06,3,0.117143,0.225714,0.030000,2.290000,9.348571,-0.897892,0

Hasta aquí hemos logrado la estructuración de la base de datos epidemiológica y meteorológica.

# Adicionar al dataset los atributos meteorológicos rezagados con un rezago hasta de 16 semanas.

In [ ]:
# Lista de variables meteorológicas
variables_meteo = ['temp', 'temp_max', 'temp_min',
       'hum_esp', 'hum_rel', 'prec', 'dias_lluvia', 'vel_vi', 'vel_vi_max',
       'vel_vi_min', 'uv', 'soi', 'sst'
]

# Número máximo de rezagos
max_lag = 16

# Iniciar el DataFrame de rezagos a partir del original
df_semanal_meteo_epi_rezagos = df_semanal_meteo_epi.copy()

# Generar rezagos
for var in variables_meteo:
    for lag in range(1, max_lag + 1):
        df_semanal_meteo_epi_rezagos[f"{var}_lag_{lag}"] = df_semanal_meteo_epi_rezagos[var].shift(lag)

# Ver resultado
df_semanal_meteo_epi_rezagos.head(15)

In [ ]:
df_semanal_meteo_epi_rezagos.columns    
df_semanal_meteo_epi_rezagos.tail(5)

In [ ]:
df_semanal_meteo_epi_rezagos.to_excel(r"C:\Users\marco\OneDrive - Universidad de Antioquia\Documentos\2_recursos_ensenanza\5_arima\6_datos_arima\4_base_datos_consolidada\datos_semanal_meteo_epi_rezagos.xlsx", index=False)

Tarea de resumir esta limpieza, **remuestreo** y fusion de datos, en una sola diapositiva.